service: agenda-backend-api
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 30

custom:
  webpack:
    webpackConfig: ./webpack.config.js

functions:
  api:
    handler: ./src/app/http/api.handler
    events:
      - http:
          path: /api
          method: ANY
      - http:
          path: /api/{proxy+}
          method: ANY

  webhook:
    handler: ./src/app/http/webhook.handler
    events:
      - http:
          path: /webhook
          method: ANY
      - http:
          path: /webhook/{proxy+}
          method: ANY
