service: agenda-backend-api
frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 30

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    keepOutputDirectory: true
  serverless-offline:
    useChildProcesses: true

functions:
  webhook:
    handler: ./src/function/http/webhook.handler
    events:
      - http:
          path: /webhook
          method: ANY
      - http:
          path: /webhook/{proxy+}
          method: ANY
